# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSUrM0b-_ijhtqFxl8CPu2Xd4eosNk65
"""

def remove_all(A,Key):
  A2 = []
  for x in A:
    if x != Key:
      A2.append(x)
  return A2

A = [22, 55, 66, 77, 55, 55, 22, 99]
B =[20,30,70,40,50,60,70]
C = [12,56,45,12,13,13,13,12,15]
print(remove_all(A,55))
print(remove_all(B,70))
print(remove_all(C,12))

def change_all(A,Key,New):
  A2 =[]
  for x in A:
    if x == Key:
      A2.append(New)
    else:
      A2.append(x)
  return A2

print(A)
print(change_all(A,55,100))
print(B)
print(change_all(B,70,90))

def reverse(A):
  B =[]
  for x in A[len(A)-1::-1]:
    B.append(x)
  return B

D =[10, 20, 30, 40, 50, 60]
B2 = [25,35,75,45,55,65,75,65]
print(reverse(D))
print(reverse(B2))

def insert_at_index(A, B, i):
   return A[:i] + B + A[i:]

E = [10, 20, 30, 40, 50, 60]
F =[65, 75, 85]
G = [67,89,45,23,12]
print(insert_at_index(E,F,3))
print(insert_at_index(F,E,1))
print(insert_at_index(G,F,0))

def  add_value(A, v):
  New = []
  for x in A:
    New.append(x + v)
  return New

print(F)
print(add_value(F,10))
print(G)
print(add_value(G,15))

def partition(A, key):
  P1 =[]
  P2 =[]
  for x in A:
    if x <= key:
      P1.append(x)
    else:
      P2.append(x)
  return P1 + P2

Z =[2, 5, 4, 7, 6, 8, 4, 6, 1, 2, 9, 8, 4, 3, 7]
print(Z)
print(partition(Z,4))
N = [12,14,2,3,5,3,3,4,5,9]
print(N)
print(partition(N,4))

def swap_adjacent(A):
  New =[]
  New.append(A[0])
  for i in range(len(A)):
     if i % 2 == 0:
       New.append(A[i+1])
     else:
      New.append(A[i-1])
  return New

S = [22, 55, 66, 77, 55, 56, 22, 99]
print(swap_adjacent(S))
print(N)
print(swap_adjacent(N))

def add_lists(A,B):
  largest = len(A) if len(A) > len(B) else len(B)
  new = []
  for i in range(largest):
    if i < len(A) and i < len(B):
        new.append(A[i] + B[i])
    elif i < len(A):
         new.append(A[i])
    else:
      new.append(B[i])
  return new

T= [10,20,30,40,50]
R = [1,2,3]
S= [15, 65]
print(add_lists(T,R))
print(add_lists(T,S))